version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${HOSTNAME}/gitlab"
        gitlab_rails['gitlab_shell_ssh_port'] = "${ALTERNATE_SSH_PORT}"
        registry_external_url "https://${HOSTNAME}:${REGISTRY_PORT}"
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_issuer'] = "omnibus-gitlab-issuer"
        gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['gitlab']
        gitlab_rails['omniauth_block_auto_created_users'] = true
        gitlab_rails['omniauth_providers'] = [
          {
            "name" => "github",
            "app_id" => "${APP_ID}",
            "app_secret" => "${APP_SECRET}",
            "args" => { "scope" => "user:email" }
          }
        ]
    ports:
      - '${GITLAB_PORT}:443'
      - '${ALTERNATE_SSH_PORT}:22'
      - '${REGISTRY_PORT}'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
      - 'registry:/var/opt/gitlab/gitlab-rails/shared/registry'
      - './secrets/gitlab.crt:/etc/gitlab/ssl/${HOSTNAME}.crt:ro'
      - './secrets/gitlab.key:/etc/gitlab/ssl/${HOSTNAME}.key:ro'
  registry:
    image: 'registry:2'
    restart: always
    environment:
      REGISTRY_LOG_LEVEL: info
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: omnibus-gitlab-issuer
      REGISTRY_AUTH_TOKEN_REALM: "https://${HOSTNAME}/gitlab/jwt/auth"
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /var/opt/gitlab/registry/gitlab-registry.crt
      REGISTRY_HTTP_SECRET: "${HTTP_SECRET}"
    expose:
      - '5000'
    ports:
      - '${REGISTRY_PORT}:5000'
    volumes:
      - 'data:/var/opt/gitlab:ro'
      - 'registry:/var/lib/registry'

volumes:
  config:
    external:
      name: gitlab_config
  logs:
    external:
      name: gitlab_logs
  data:
    external:
      name: gitlab_data
  registry:
    external:
      name: gitlab_registry
